### ISSUE TITLE
Negative with block times glitch

### ISSUE THREAD

**Issue by ashneverdawn** [kadena-io/block-explorer#29]
On Windows using Firefox browser, I ran into this glitch on testnet:
![explorer-bug](https://user-images.githubusercontent.com/8341280/105102954-b93b1180-5a7d-11eb-9669-0566ca71b4e5.png)

I had switched tabs for a few minutes and when I came back, the times glitched out. ~~Only seems to happen on testnet, haven't ran into this on mainnet.~~ Has anyone else run into this before?

Edit: actually I did see it on mainnet, (maybe to a lesser extent?):
![explorer-bug-mainnet](https://user-images.githubusercontent.com/8341280/105103722-08ce0d00-5a7f-11eb-8b1c-69fb2cf8937f.png)

**Comment by mightybyte** [comment]
This means that your computer's clock is wrong.  I've put some thought into this and haven't been able to come up with a good way of prevent this other than the user setting the time properly on their computer.

**Comment by enobayram** [comment]
Based on @mightybyte's comment above and the age of the discussion, I'm closing this issue.
