### ISSUE TITLE
Incorporate balance lookup to the explorer

### ISSUE THREAD

**Issue by Thanos420NoScope** [kadena-io/block-explorer#34]
Adding [this](https://github.com/kadena-community/kadena-balance) to the explorer to allow balance lookup directly from the explorer would be pretty useful.

Maybe a third choice on the search dropdown menu to query balances
![image](https://user-images.githubusercontent.com/6309193/119161812-b6e6c500-ba27-11eb-9b13-58d6afaef4e2.png)

**Comment by enobayram** [comment]
Thank you opening this issue @Thanos420NoScope, seems like the request here got implemented by #39 a while ago, so I'm closing this issue.
