### ISSUE TITLE
An unexpected error occured when processing request key

### ISSUE THREAD

**Issue by fabifighter007** [kadena-io/block-explorer#41]
An unexpected error occured when processing request key: mELG25Mdn09hGCwJFYnGHF37ds_OLAz5rCZGMSLitlE Help us make our tools better by filing an issue with the below message at www.github.com/kadena-io/block-explorer : "Error in $: Failed reading: not a valid json value"

https://explorer.chainweb.com/mainnet/tx/mELG25Mdn09hGCwJFYnGHF37ds_OLAz5rCZGMSLitlE

**Comment by mightybyte** [comment]
Fixed.  It displays a better error message now.
