### ISSUE TITLE
"Error in $: Failed reading: not a valid json value"

### ISSUE THREAD

**Issue by jittakorn-bit** [kadena-io/block-explorer#43]
An unexpected error occured when processing request key: 5pUTa7p9IGHcUM8AoTXA8gLnx5OecZHN8TFGooQAR9A
Help us make our tools better by filing an issue with the below message at www.github.com/kadena-io/block-explorer :
"Error in $: Failed reading: not a valid json value"

https://explorer.chainweb.com/mainnet/tx/5pUTa7p9IGHcUM8AoTXA8gLnx5OecZHN8TFGooQAR9A

**Comment by mightybyte** [comment]
Fixed
