### ISSUE TITLE
Empty response with error code 404

### ISSUE THREAD

**Issue by liquidityqloud** [kadena-io/block-explorer#45]
Here's the explorer link: https://explorer.chainweb.com/mainnet/txdetail/LjXe3rrXfyJyjtU6-7YOUvv3gh1AaAhcALo3ETd82T8

![image](https://user-images.githubusercontent.com/79758400/142755704-e6bb7ce4-d6a6-44fb-be54-e7b8ace8c33c.png)

**Comment by enobayram** [comment]
Hi @liquidityqloud, sounds like this was a transient issue with the indexer not having indexed the relevant transaction at the time of opening this issue, so I'm closing it.
