### ISSUE TITLE
Block payload query failed

### ISSUE THREAD

**Issue by fiankr** [kadena-io/block-explorer#50]
This [block](https://explorer.chainweb.com/mainnet/chain/1/block/s50t7-d4gvF-VezAD0SxWp5d2ii88wCjU9l1nQjBlB4/txs) cant seem to be displayed and shows this error on the page:

```
Block payload query failed: Error in $.transactions[2][0]: Error in $.payload: parsing Exec failed, expected Object, but encountered Null
```

**Comment by enobayram** [comment]
Hi @fiankr, thank your for the issue. Seems like this bug got resolved as part of [the block transactions view redesign](https://github.com/kadena-io/block-explorer/pull/75), so I'm closing this issue.
