### ISSUE TITLE
Layout is wrong when viewing large transactions

### ISSUE THREAD

**Issue by CryptoPascal31** [kadena-io/block-explorer#76]
Transactions with long lines can't be properly seen in `/txdetail`:
eg: https://explorer.chainweb.com/testnet/txdetail/vhSV77Z4G0Vxid9kqkN-7l9JbydcV2etlKTvjj4rKkQ

The issue comes from both the Code and Data sections.

IMO, lines should be broken, or an horizontal scroll added.

**Comment by CryptoPascal31** [comment]
Confirm that it works.
Thank you  @enobayram

**Comment by enobayram** [comment]
Thank you for the confirmation @CryptoPascal31!
