### ISSUE TITLE
"Error in $.result: key \"data\" not present"

### ISSUE THREAD

**Issue by Abedigwig** [kadena-io/block-explorer#84]
An unexpected error occured when processing request key: Lw3OFv7NS7xViiy4Lf9WmVXCJ1-OkooBe9RDWVHEB8E
Help us make our tools better by filing an issue with the below message at www.github.com/kadena-io/block-explorer :
"Error in $.result: key \"data\" not present"

**Comment by enobayram** [comment]
Thank you for opening this issue @Abedigwig, as a side note, the "Transaction Detail" view is able to handle it: https://explorer.chainweb.com/mainnet/txdetail/Lw3OFv7NS7xViiy4Lf9WmVXCJ1-OkooBe9RDWVHEB8E

The https://explorer.chainweb.com/mainnet/tx/Lw3OFv7NS7xViiy4Lf9WmVXCJ1-OkooBe9RDWVHEB8E view needs to be fixed as well, of course
